import SwiftUI
import UniformTypeIdentifiers

/// Owns the app's split-view shell and connects note-store state to its sidebar and editor.
struct ContentView: View {
    /// Shared store bound into both columns of the split view.
    @Bindable var store: NotesStore
    /// Routes scene commands to the active Notra window.
    @State private var commandContext: NotraCommandContext
    /// Lets the system manage sidebar visibility while the split view has regular width.
    @State private var columnVisibility: NavigationSplitViewVisibility = .automatic
    /// Keeps the editor on top when the split view collapses in narrow widths.
    @State private var preferredCompactColumn: NavigationSplitViewColumn = .sidebar
    /// Search query owned by the sidebar, cleared after a new note is created.
    @State private var searchText = ""
    /// Keeps inspector presentation at the split-view boundary, shared by every platform.
    @State private var isAttachmentInspectorPresented = false
    /// Carries an inspector insertion into the editor, which consumes and clears the request.
    @State private var attachmentToInsert: TextBundleAsset?
    /// Monotonic request that moves focus into a newly created note.
    @State private var editorFocusRequest = 0
    /// Monotonic request carrying a selected imported attachment into the editor.
    @State private var attachmentSelectionRequest = MarkdownAttachmentSelectionRequest.empty
    /// Presentation state for the shared attachment file importer.
    @State private var isAttachmentFileImporterPresented = false
    /// Keeps one export task active so repeated menu requests cannot overlap.
    @State private var exportTask: Task<Void, Never>?
    /// Holds generated bytes until the native file exporter presents a save location.
    @State private var pendingFileExport: PendingNoteFileExport?
    /// User-selected initial Markdown for new note creation.
    @AppStorage(NoteSettingKey.startNewNoteWith) private var startNewNoteWith =
        NoteStartContent.defaultValue.rawValue
    /// Uses the same preview font for PDF export as the interactive Markdown preview.
    @AppStorage(AppearanceSettingKey.previewFontName) private var previewFontName = AppearanceFont.defaultName

    init(store: NotesStore) {
        self.store = store
        _commandContext = State(initialValue: NotraCommandContext(store: store))
    }

    var body: some View {
        @Bindable var commands = commandContext

        NavigationSplitView(
            columnVisibility: $columnVisibility,
            preferredCompactColumn: $preferredCompactColumn
        ) {
            NotesSidebar(
                store: store,
                isEditing: commands.isEditing,
                searchText: $searchText,
                createNote: createNote,
                exportNote: requestExport
            )
            .navigationSplitViewColumnWidth(min: 220, ideal: 260, max: 360)
        } detail: {
            NoteEditorPane(
                store: store,
                isEditing: $commands.isEditing,
                editorCommandRequest: commands.editorCommandRequest,
                isAttachmentInspectorPresented: $isAttachmentInspectorPresented,
                attachmentToInsert: $attachmentToInsert,
                editorFocusRequest: editorFocusRequest,
                commandEditorFocusRequest: commands.editorFocusRequestID,
                createNote: createNote,
                attachmentSelectionRequest: attachmentSelectionRequest,
                requestAttachmentSelection: presentAttachmentFileImporter,
                requestShare: { commandContext.requestExport(.sharePDF) },
                shareState: commands.shareState
            )
        }
        // Let the sidebar take space from the editor instead of overlaying it on iPad.
        .navigationSplitViewStyle(.balanced)
        // Placing the inspector outside the split view preserves its system sidebar navigation.
        // An inspector on the detail content can hide the sidebar toggle on iPadOS 26.
        .inspector(isPresented: $isAttachmentInspectorPresented) {
            AttachmentInspectorView(
                store: store,
                isEditing: commands.isEditing,
                insertAttachment: { attachmentToInsert = $0 },
                removeTag: removeTag
            )
        }
        .task {
            await store.loadNotes()
        }
        .focusedSceneValue(commandContext)
        .onChange(of: store.selectedNoteID) {
            preferredCompactColumn = store.selectedNoteID == nil ? .sidebar : .detail
            attachmentToInsert = nil
            if !store.hasSelection {
                isAttachmentInspectorPresented = false
            }
            commandContext.shareState = .idle
            Task {
                await store.selectionChanged()
            }
        }
        .onChange(of: commandContext.newNoteRequestID) {
            createNote()
        }
        .onChange(of: commandContext.attachmentRequestID) {
            presentAttachmentFileImporter()
        }
        .onChange(of: commandContext.isEditing) {
            commandContext.shareState = .idle
        }
        .onChange(of: commandContext.exportRequest) {
            guard let request = commandContext.exportRequest,
                  let note = store.selectedNoteSummary
            else {
                return
            }

            requestExport(note, request.action)
        }
        .sheet(isPresented: $commands.isKeyboardShortcutsPresented) {
            NavigationStack {
                KeyboardShortcutsView()
            }
            #if os(macOS)
            .frame(minWidth: 620, idealWidth: 720, minHeight: 540, idealHeight: 640)
            #else
            .presentationDetents([.large])
            .presentationDragIndicator(.visible)
            #endif
        }
        .alert("Notra", isPresented: errorBinding) {
            Button("OK") {
                store.errorMessage = nil
            }
        } message: {
            Text(store.errorMessage ?? "")
        }
        .modifier(attachmentFileImporter)
        .fileExporter(
            isPresented: Binding(
                get: { pendingFileExport != nil },
                set: { isPresented in
                    if !isPresented {
                        pendingFileExport = nil
                    }
                }
            ),
            document: pendingFileExport?.document,
            contentType: pendingFileExport?.contentType ?? .data,
            defaultFilename: pendingFileExport?.suggestedFilename
        ) { result in
            if case let .failure(error) = result {
                AppLog.error("Failed to save note export: \(error.localizedDescription)")
                store.errorMessage = error.localizedDescription
            }
            pendingFileExport = nil
        }
    }

    /// Routes inspector tag changes through the same store used by the sidebar and editor.
    private func removeTag(_ tag: NoteTag) {
        Task {
            await store.removeTag(tag)
        }
    }

    /// Adapts the store's optional error into the Boolean binding expected by `alert`.
    private var errorBinding: Binding<Bool> {
        Binding {
            store.errorMessage != nil
        } set: { isPresented in
            if !isPresented {
                store.errorMessage = nil
            }
        }
    }

    /// Creates a note and moves compact layouts into focused editing when selection changes.
    private func createNote() {
        Task {
            let previousSelectionID = store.selectedNoteID
            let startContent = NoteStartContent.resolved(rawValue: startNewNoteWith)
            await store.createNote(initialMarkdown: startContent.initialMarkdown)
            searchText = ""
            guard store.selectedNoteID != previousSelectionID else {
                return
            }

            preferredCompactColumn = .detail
            commandContext.isEditing = true
            editorFocusRequest += 1
        }
    }

    /// Builds the importer modifier while keeping imported URLs in the root content state.
    private var attachmentFileImporter: AttachmentFileImporterModifier {
        AttachmentFileImporterModifier(isPresented: $isAttachmentFileImporterPresented) { url in
            attachmentSelectionRequest = MarkdownAttachmentSelectionRequest(
                id: attachmentSelectionRequest.id + 1,
                url: url
            )
        } onError: { error in
            store.errorMessage = error.localizedDescription
        }
    }

    /// Requests platform file selection for an attachment link.
    private func presentAttachmentFileImporter() {
        AppLog.info("Presenting attachment file importer from root content")
        isAttachmentFileImporterPresented = true
    }

    private func requestExport(_ note: NoteSummary, _ action: NoteExportAction) {
        guard !commandContext.isEditing, exportTask == nil else {
            return
        }

        exportTask = Task { @MainActor in
            defer { exportTask = nil }

            if action == .sharePDF {
                commandContext.shareState = .generating
            }

            do {
                let payload = try await store.exportPayload(for: note)
                switch action {
                case .sharePDF:
                    let item = try await NotePDFExporter().export(snapshot: pdfSnapshot(for: payload))
                    NoteSharePresenter.present(fileURL: item.fileURL)
                    commandContext.shareState = .idle
                case .exportPDF:
                    let item = try await NotePDFExporter().export(snapshot: pdfSnapshot(for: payload))
                    presentFileExport(
                        fileURL: item.fileURL,
                        contentType: .pdf,
                        suggestedFilename: item.suggestedFilename
                    )
                case .exportMarkdown:
                    let item = try NoteMarkdownExporter().export(payload: payload)
                    presentFileExport(
                        fileURL: item.fileURL,
                        contentType: .notraMarkdown,
                        suggestedFilename: item.suggestedFilename
                    )
                }
            } catch {
                AppLog.error("Failed to prepare note export: \(error.localizedDescription)")
                store.errorMessage = error.localizedDescription
                if action == .sharePDF {
                    commandContext.shareState = .failed
                }
            }
        }
    }

    private func pdfSnapshot(for payload: NoteExportPayload) -> NotePDFSnapshot {
        NotePDFSnapshot(
            markdown: payload.markdown,
            noteURL: payload.noteURL,
            previewFontName: previewFontName,
            suggestedFilename: payload.suggestedFilename
        )
    }

    private func presentFileExport(
        fileURL: URL,
        contentType: UTType,
        suggestedFilename: String
    ) {
        guard pendingFileExport == nil else {
            return
        }

        do {
            let data = try Data(contentsOf: fileURL)
            pendingFileExport = PendingNoteFileExport(
                document: NoteFileExportDocument(data: data),
                contentType: contentType,
                suggestedFilename: suggestedFilename
            )
        } catch {
            AppLog.error("Failed to load note export: \(error.localizedDescription)")
            store.errorMessage = error.localizedDescription
        }
    }
}

#Preview {
    ContentView(store: NotesStore(repository: TextBundleNoteRepository(rootURL: .temporaryDirectory)))
}
